### ISSUE TITLE
Set default font size and line weight through user settings (Annotations tools)

### ISSUE THREAD

**Issue by a-shafaat** [adobe/pdf-embed-api-samples#10]
### Expected Behaviour
1. being able to set default size of lines and texts. (like color)
2. size of texts and lines should be the last size used by user. (like color)
i expect to be able to set default **drawing tool** weight and **text comment** font size through user setting. i can only set default colors of tools.
beside that, when i draw a line and then change the color and weight of it, the next drawing will be the same color but not the same weight! (same for text comment)
### Actual Behaviour

1. not able to set default size of lines and texts.
2. size of texts and lines is fixed and not related to last settings. (like color)

**Comment by cfjedimaster** [comment]
Hi, issues here should address problems in the samples for this repo. For questions/issues using Embed, please use our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
