### ISSUE TITLE
APP_RENDERING_FAILED not fired even though UI gives out error message

### ISSUE THREAD

**Issue by jeremyimmanuel** [adobe/pdf-embed-api-samples#11]
### Expected Behaviour

`APP_RENDERING_FAILED` event is fired if viewer fails to load a file. (corrupted pdf files, renamed non pdf files to `.pdf` ext)

### Actual Behaviour

Viewer gives an error on the UI but the event is not fired at all.

### Reproduce Scenario (including but not limited to)

Attach a non-pdf file, or a non-pdf file that you renamed to a pdf.

**Comment by cfjedimaster** [comment]
Hi, issues here should address problems in the samples for this repo. For questions/issues using Embed, please use our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
