### ISSUE TITLE
Grab PDF file from a VFS

### ISSUE THREAD

**Issue by jffortier249** [adobe/pdf-embed-api-samples#14]
Hi, sorry my english is not perfect, not a web developper, only searching a solution to fix an iOS13+ browser change in behaviour regarding PDF file.
Application is Filemaker Go on iPhone/iPad, so it will use the Safari browser to view web document.

### Expected Behaviour
view the pdf file

### Actual Behaviour
error, can't preview
File preview error, not available reload to try again

### Reproduce Scenario (including but not limited to)
Use a source file hosted by a Virtual File Service like HFS from Rejetto https://rejetto.com/hfs/

#### Platform and Version
iOS14 Safari, Win10 Chrome

#### Sample Code that illustrates the problem
The demo code from https://www.adobe.io/document-services/apis/pdf-embed/

#### Logs taken while reproducing problem

The demo file works, 
I got my API key, test the demo file on my website.
Test the demo code and my key with a PDF hosted on my website, all work

The only probleme is the .js is not waiting or asking properly
The log show a request for data, the web page indicate error and the VFS never send the file.
Spoke with the dev of HFS and it as to do with request/answer/expectation of the .js that is the cause.

That same URL enter in any web browser will download the file right away, so the VFS is not the issue.

Thanks

**Comment by cfjedimaster** [comment]
Hi, issues here should address problems in the samples for this repo. For questions/issues using Embed, please use our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
