### ISSUE TITLE
postMessage for Adobe Embed API

### ISSUE THREAD

**Issue by SahandSoltanieh** [adobe/pdf-embed-api-samples#15]
Does Adobe Embed API have anyway of handling postMessage api requests?

**Comment by cfjedimaster** [comment]
Hi, issues here should address problems in the samples for this repo. For questions/issues using Embed, please use our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
