### ISSUE TITLE
Not able to View the EA forms document in PDF-emded viewer 

### ISSUE THREAD

**Issue by vinay2707** [adobe/pdf-embed-api-samples#16]
### Expected Behaviour
The uploaded document and pdf-emdeb viewer document should be same.

### Actual Behaviour
pdf-emded viewer document is not matching with uploaded document

#### Steps to Reproduce

**Original Document Before uploading to pdf-emded viewer**
Total number of pages is 38

[maa_human_v1.19.0.2_Result.pdf](https://github.com/adobe/pdf-embed-api-samples/files/8254105/maa_human_v1.19.0.2_Result.pdf)

**PDF Document after viewed in PDF-emdeb viewer and downloaded
Total no of pages is 28 pages**

![image](https://user-images.githubusercontent.com/101565365/158398325-0bd5734f-f1a5-44d0-89b5-350d17e35791.png)

In Viewer content are getting overlap 
![image](https://user-images.githubusercontent.com/101565365/158399000-51adae60-422e-4011-a7b2-2805edb57aac.png)

**Comment by cfjedimaster** [comment]
Hi, issues here should address problems in the samples for this repo. For questions/issues using Embed, please use our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
