### ISSUE TITLE
pdf embed inside a web component

### ISSUE THREAD

**Issue by rrrepos** [adobe/pdf-embed-api-samples#4]
I am trying to create a component and embed the pdf viewer inside it by passing the relevant pdf. However, all the examples using LINE_IN or SIZED_CONTAINER which seems appropriate to my use-case needs an element ID that is accessible from the main DOM. However, I would like it contained within my component viz. shadowDOM. Is there a way of specifying the DivId by a element instead of an Id? If so, I can pass the shadowDom element object to the AdobeDC class

Thanks

**Comment by cfjedimaster** [comment]
@rrrepos I'm sorry no one responded to you. I work on the Document Services team at Adobe and I just ran into this issue myself. I'm going to report it internally, and also reach out to the team on how we handle/respond/etc to issues on this repo.

**Comment by cfjedimaster** [comment]
Closing this as I've reported it internally.

**Comment by shiny0-ctrl** [comment]
Hello, I have encountered the same problem. Is there any solution now?

**Comment by cfjedimaster** [comment]
Sorry no.
