### ISSUE TITLE
Enforce refresh pdf file content in same iframe for multiple pdf files via <input> tag.

### ISSUE THREAD

**Issue by kern-ding** [adobe/pdf-embed-api-samples#5]
### Expected Behaviour
Open 1st pdf file via <input>, passing the file as URL (URL.createObjectURL()) to 
this.AdobeDCView.previewFile({content: {location}, metaData: {fileName, id}}, viewerConfig);
It render correctly.

Open 2nd pdf file via <input, same steps as above; it eventually calls AdobeDCView.previewFile with a different URL, expected to see the new pdf file rendered.

### Actual Behaviour
It's the 1st pdf rendered in iframe.

Is there a way to enforce refreshing the pdf files?

**Comment by cfjedimaster** [comment]
Hi, issues here should address problems in the samples for this repo. For questions/issues using Embed, please use our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
