### ISSUE TITLE
Add JSON encoded form fields and values to "metadata" parameter on Save

### ISSUE THREAD

**Issue by cl0rkster** [adobe/pdf-embed-api-samples#7]
It would be extremely useful to have the PDF form fields and values added as a JSON object to the metadata parameter when "Save" is clicked on the PDF.  At present, the large size of some PDFs makes transmitting them to a server via javascript a substantial challenge.  There are size issues, encoding issues, and then issues of actually pulling said form fields and values from the PDF once the BLOB reaches the server.

The use case of allowing consumers to use an actual PDF to enter form data on the internet instead of HTML forms without the document support (or some side-by-side amalgamation) would be incredibly well received.

**Comment by samuelkarani** [comment]
agree!

**Comment by cfjedimaster** [comment]
Hi, issues here should address problems in the samples for this repo. For questions/issues using Embed, please use our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
