### ISSUE TITLE
problems using pdf files hosted in azure blobstorage

### ISSUE THREAD

**Issue by cdreckmann** [adobe/pdf-embed-api-samples#8]
I am trying to use the API with files hosted in azure blobstorage, the error it gives me is the following:

File preview error
File preview not available, please reload to try again.

regards.

**Comment by cfjedimaster** [comment]
Hi, issues here should address problems in the samples for this repo. For questions/issues using Embed, please use our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
